DROP TABLE IF EXISTS KEEPASS;
DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
  `USER_ID` varchar(255) NOT NULL PRIMARY KEY,
  `LAST_ACCESS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SID_CREATED` int unsigned NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE KEEPASS (
  `SESSION_ID` varchar(255) NOT NULL PRIMARY KEY,
  `PSW` longtext,
  `CREATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USER_ID` varchar(255) NOT NULL,
  `PUBLIC_KEY` varchar(512) NOT NULL,

  FOREIGN KEY (`USER_ID`) REFERENCES USER(USER_ID)
) ENGINE=InnoDB;
